{% set name = "autoscraper" %}
{% set version = "1.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autoscraper-{{ version }}.tar.gz
  sha256: 281901477fb69aa09aa235abbd15bb38c46df1682c2cad504d0ac1ee0b6b81d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - bs4
    - lxml

test:
  imports:
    - autoscraper
  # Disable pip check test due to it not working for detecting bs4/beautiful soup dependency
  # commands:
  #  - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alirezamika/autoscraper
  summary: A Smart, Automatic, Fast and Lightweight Web Scraper for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
